name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI
on:
  push:
  pull_request:
    types: [opened, reopened]
  release:
    types: [published]
jobs:
  build-and-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install the project
        run: uv sync --locked --dev

      - name: Pre Commit
        run: uv run pre-commit run --all-files

      - name: Test
        run: uv run pytest

      - name: Build
        run: uv build

      - name: Publish distribution 📦 to Test PyPI
        if: contains(github.ref, 'refs/heads/master')
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_TOKEN: ${{ secrets.test_pypi_password }}
        run: uv publish --index testpy
      - name: Publish distribution 📦 to PyPI
        if: contains(github.ref, 'refs/tags/v')
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_TOKEN: ${{ secrets.pypi_password }}
        run: uv publish
